
spring:
  rabbitmq:
    host: 192.168.1.121
    port: 5672
    password: 123
    username: yinyao
    virtual-host: /test
    listener:
      simple:
        #设置消费端手动 ack
        acknowledge-mode: manual
        #在单个请求中处理的消息个数，他应该大于等于事务数量(unack的最大数量)
        prefetch: 2
        concurrency: 2
#        容器将根据工作负载动态调整并发性
        max-concurrency: 10

